import React, { ReactNode } from "react";
import "../globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "APS",
  description: "Generated by create next app",
};
// Define the types for the props
interface LayoutProps {
  children: ReactNode; // Children can be any valid React node
  className?: string; // className is optional
}

const Layout: React.FC<LayoutProps> = ({ children, className = "" }) => {
  return (
    <div
      className={`w-full h-full inline-block z-10 repeating-bg opacity-85 px-32 dark:bg-black xl:p-24 lg:p-16 md:p-12 overflow-hidden sm:p-8 ${className}`}
    >
      {children}
    </div>
  );
};

export default Layout;
