import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import PageNavigation from "./components/PageNavigation";
import { Providers } from "./providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export const metadata: Metadata = {
  title: "APS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} font-mont bg-[#F2F3F2] w-full min-h-screen dark:bg-dark dark:text-light`}
      >
        <Providers>
          <NavBar />
          {children}
          <Footer />
          <PageNavigation />
        </Providers>
      </body>
    </html>
  );
}
